const defaultActions=[{id:1,title:"机に5分座る",time:"夜",streak:4,done:false},{id:2,title:"SNSを開く前に深呼吸する",time:"いつでも",streak:2,done:false},{id:3,title:"今日できたことを1つ書く",time:"寝る前",streak:7,done:true}];
let actions=JSON.parse(localStorage.getItem('weakness-actions')||'null')||defaultActions;let currentId=null;
const $=s=>document.querySelector(s);const list=$('#action-list');
function save(){localStorage.setItem('weakness-actions',JSON.stringify(actions))}
function render(){const done=actions.filter(x=>x.done).length,total=actions.length,pct=total?Math.round(done/total*100):0;$('#done-count').textContent=done;$('#total-count').textContent=total;$('#progress-percent').textContent=`${pct}%`;$('#progress-ring').style.background=`conic-gradient(#fff ${pct*3.6}deg,#938af3 0)`;list.innerHTML=actions.map(a=>`<button class="action-card ${a.done?'completed':''}" data-id="${a.id}"><span class="check">${a.done?'✓':''}</span><span><h3>${a.title}</h3><p>${a.time}に取り組む</p></span><span class="streak">🔥 ${a.streak}日</span></button>`).join('');const recorded=actions.filter(x=>x.done).length;$('#week-rate').textContent=`${Math.min(100,recorded*25+25)}%`;$('#change-copy').textContent=`記録 ${recorded+2}日`;$('#week-chart').innerHTML=['月','火','水','木','金','土','日'].map((d,i)=>`<div class="bar ${i<recorded+2?'done':''}" style="height:${32+i%3*16}px"><span>${d}</span></div>`).join('')}
function renderRanks(){const me=Math.min(100,actions.filter(a=>a.done).length*25+25);const people=[['美咲',92,'美'],['あなた',me,'佐'],['健太',68,'健'],['梨花',55,'梨']].sort((a,b)=>b[1]-a[1]);$('#ranking').innerHTML=people.map((p,i)=>`<article class="rank-row"><span class="rank-number">${i+1}</span><span class="rank-avatar">${p[2]}</span><span><strong>${p[0]}</strong><small>今週の実行率</small></span><span class="rank-score">${p[1]}%</span></article>`).join('')}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#page-title').textContent={"home-view":"今日の一歩","chat-view":"相談する","review-view":"ふりかえる","group-view":"みんなの進捗"}[id];if(id==='group-view')renderRanks()}
list.addEventListener('click',e=>{const card=e.target.closest('[data-id]');if(!card)return;currentId=Number(card.dataset.id);const a=actions.find(x=>x.id===currentId);$('#dialog-action').textContent=a.title;$('#reason-area').hidden=true;$('#result-dialog').showModal()});
$('#complete-action').addEventListener('click',()=>{const a=actions.find(x=>x.id===currentId);a.done=true;a.streak++;save();render()});
$('#skip-action').addEventListener('click',e=>{e.preventDefault();$('#reason-area').hidden=false});
document.querySelectorAll('.reason-grid button').forEach(b=>b.addEventListener('click',()=>{$('#result-dialog').close();const a=actions.find(x=>x.id===currentId);a.done=false;save();render()}));
$('#add-action').onclick=()=>$('#add-dialog').showModal();$('#close-add').onclick=()=>$('#add-dialog').close();$('#add-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target);actions.push({id:Date.now(),title:d.get('action'),time:d.get('time'),streak:0,done:false});save();render();e.target.reset();$('#add-dialog').close()});
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function sendChat(text){if(!text.trim())return;$('#chat-log').insertAdjacentHTML('beforeend',`<div class="message me">${text}</div>`);$('#chat-input').value='';setTimeout(()=>$('#chat-log').insertAdjacentHTML('beforeend','<div class="message ai">話してくれてありがとう。その場面で、いちばん小さく変えられそうなことは何でしょう？</div>'),250)}
$('#chat-form').addEventListener('submit',e=>{e.preventDefault();sendChat($('#chat-input').value)});document.querySelectorAll('.suggestions button').forEach(b=>b.onclick=()=>sendChat(b.textContent));
const now=new Date();$('#today-label').textContent=`${now.getMonth()+1}月${now.getDate()}日 · ${['日','月','火','水','木','金','土'][now.getDay()]}曜日`;render();renderRanks();
